services:
  auth-svc:
    container_name: auth-svc
    build:
      context: ../..
      dockerfile: ./apps/auth-svc/Dockerfile
    restart: unless-stopped
    ports:
      - 2001:3001
    depends_on:
      - auth-db
    env_file:
      - ../../envs/.env.dev

  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: unless-stopped
    ports:
      - 2432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data-lake:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: isnex-data-lake
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "1000:9000"
      - "1001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ../../minio/data:/data

volumes:
  postgres_data:

networks:
  default:
    name: isnex-net
    external: true
