x-kong-image: &kong-image kong:3.9.1-ubuntu

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  kong:
    image: *kong-image
    container_name: kong-dbless
    user: "${KONG_USER:-kong}"
    environment:
      KONG_PROMETHEUS_ENABLED: "on"
      KONG_PREFIX: /var/run/kong
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://kong:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    read_only: true
    volumes:
      - ../../apps/api-gateway/declarative:/kong/declarative
      - ../../apps/api-gateway/tmp_volume:/tmp
      - ../../apps/api-gateway/prefix_volume:/var/run/kong
    security_opt:
      - no-new-privileges

  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: zipkin
    ports:
      - 8411:9411

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "8090:9090"
    volumes:
      - ../../apps/api-gateway/config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.3.0-17718666199-ubuntu
    container_name: grafana
    ports:
      - "8500:3000"

  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak
  #   environment:
  #     DB_VENDOR: postgres
  #     DB_ADDR: kong-database
  #     DB_DATABASE: kong
  #     DB_USER: kong
  #     DB_PASSWORD: mykongpassword
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_HOSTNAME: "http://localhost:8080"  # Set to localhost or your specific hostname
  #     KC_HOSTNAME_STRICT: "false"
  #     KEYCLOAK_FRONTEND_URL: "http://localhost:8080"  # Set to HTTP
  #     KC_HTTPS_PORT: -1  # Disable HTTPS port
  #     KC_SSL_REQUIRED: "none"
  #     KC_BOOTSTRAP_ADMIN_USERNAME: admin  # Set new environment variables for admin username
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: admin  # Set
  #   command: ["start-dev", "--http-enabled=true"]
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kong-database
  #   networks:
  #     - isnex-net

  # elasticsearch:
  #   image: elasticsearch:8.11.3
  #   container_name: elasticsearch
  #   restart: unless-stopped
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - ES_JAVA_OPTS=-Xms256m -Xmx1024m
  #     - discovery.type=single-node
  #   networks:
  #     isnex-net:
  #       ipv4_address: 172.1.1.21

  # kibana:
  #   image: kibana:8.11.3
  #   container_name: kibana
  #   restart: unless-stopped
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     isnex-net:
  #       ipv4_address: 172.1.1.22

  # logstash:
  #   image: logstash:8.11.3
  #   container_name: logstash
  #   restart: unless-stopped
  #   ports:
  #     - "5555:5555/udp"
  #     - "5044:5044"
  #     - "9600:9600"
  #   volumes:
  #     - "./logstash/:/usr/share/logstash/pipeline/"
  #   environment:
  #     - MONITORING_ENABLED=false
  #   networks:
  #     isnex-net:
  #       ipv4_address: 172.1.1.23

networks:
  default:
    name: isnex-net
    external: true
